package org.demo.codegen.generator;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.util.List;

import org.demo.codegen.meta.ColumnMeta;
import org.demo.codegen.meta.TableMeta;

public class ModelGenerator {

    // 项目固定写死
    private static final String ID_GENERATOR_NAME = "CommonGenerator";
    private static final String ID_GENERATOR_STRATEGY = "com.sinoservices.framework.core.support.id.CommonIdGenerator";

    public File generate(TableMeta t, String outDir, String modelPackage, String idColumnCfg, String versionColumnCfg) throws Exception {
        if (t == null) throw new IllegalArgumentException("TableMeta is null");

        String pkg = resolvePackage(modelPackage);
        String className = resolveModelClassName(t);

        String tableName = t.getTableName();

        String idCol = (idColumnCfg != null && idColumnCfg.trim().length() > 0)
                ? idColumnCfg.trim()
                : guessIdColumn(t.getColumns());

        String verCol = (versionColumnCfg != null && versionColumnCfg.trim().length() > 0)
                ? versionColumnCfg.trim()
                : guessVersionColumn(t.getColumns());

        StringBuilder sb = new StringBuilder();

        // package + imports
        sb.append("package ").append(pkg).append(";\n\n");
        sb.append("import java.util.Date;\n");
        sb.append("import javax.persistence.Column;\n");
        sb.append("import javax.persistence.Entity;\n");
        sb.append("import javax.persistence.GeneratedValue;\n");
        sb.append("import javax.persistence.Id;\n");
        sb.append("import javax.persistence.Table;\n");
        sb.append("import javax.persistence.Version;\n");
        sb.append("import org.hibernate.annotations.GenericGenerator;\n");
        sb.append("\n");
        sb.append("import com.sinoservices.framework.core.model.BaseModel;\n");
        sb.append("import com.sinoservices.framework.core.model.OperationLog;\n\n");

        // class javadoc（可选）
        sb.append("/**\n");
        sb.append(" * Generated by sql-query-codegen\n");
        sb.append(" * Table: ").append(tableName).append("\n");
        sb.append(" */\n");

        // class annotations
        sb.append("@Entity\n");
        sb.append("@Table(name = \"").append(escapeJavaString(tableName.toUpperCase())).append("\")\n");
        sb.append("@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)\n");
        sb.append("public class ").append(className).append(" extends BaseModel implements OperationLog {\n\n");

        // fields with //注释
        List<ColumnMeta> cols = t.getColumns();
        for (int i = 0; i < cols.size(); i++) {
            ColumnMeta c = cols.get(i);
            String comment = safeComment(c);
            sb.append("    //").append(comment).append("\n");
            sb.append("    private ").append(c.getJavaType()).append(" ").append(c.getJavaName()).append(";\n");
        }
        sb.append("\n");

        // getters/setters with annotations + addValidField
        for (int i = 0; i < cols.size(); i++) {
            ColumnMeta c = cols.get(i);

            String colName = c.getColumnName();
            String javaName = c.getJavaName();
            String javaType = c.getJavaType();
            String upper = upperFirst(javaName);
            String comment = safeComment(c);

            // Get comment block
            sb.append("    /**\n");
            sb.append("     * Get ").append(comment).append("\n");
            sb.append("     */\n");

            // special annotations
            if (idCol != null && equalsIgnoreCaseTrim(colName, idCol)) {
                sb.append("    @Column(name = \"").append(escapeJavaString(colName.toUpperCase())).append("\")\n");
                sb.append("    @GenericGenerator(name = \"").append(ID_GENERATOR_NAME).append("\", strategy = \"")
                        .append(ID_GENERATOR_STRATEGY).append("\")\n");
                sb.append("    @Id\n");
                sb.append("    @GeneratedValue(generator=\"").append(ID_GENERATOR_NAME).append("\")\n");
            } else {
                sb.append("    @Column(name = \"").append(escapeJavaString(colName.toUpperCase())).append("\")\n");
                if (verCol != null && equalsIgnoreCaseTrim(colName, verCol)) {
                    sb.append("    @Version\n");
                }
            }

            // getter
            sb.append("    public ").append(javaType).append(" get").append(upper).append("() {\n");
            sb.append("        return ").append(javaName).append(";\n");
            sb.append("    }\n\n");

            // Set comment block
            sb.append("    /**\n");
            sb.append("     * Set ").append(comment).append("\n");
            sb.append("     */\n");

            // setter
            sb.append("    public void set").append(upper).append("(").append(javaType).append(" ").append(javaName).append(") {\n");
            sb.append("        this.").append(javaName).append(" = ").append(javaName).append(";\n");
            sb.append("        addValidField(\"").append(escapeJavaString(javaName)).append("\");\n");
            sb.append("    }\n\n");
        }

        sb.append("}\n");

        File f = toJavaFile(outDir, pkg, className);
        writeUtf8(f, sb.toString());
        return f;
    }

    // ===== helpers =====

    public String resolvePackage(String pkgOrShort) {
        if (pkgOrShort == null || pkgOrShort.trim().length() == 0) {
            return "model";
        }
        return pkgOrShort.trim();
    }


    public String resolveModelClassName(TableMeta t) {
        return t.getClassName() + "Model";
    }

    private File toJavaFile(String outDir, String pkg, String className) {
        String base = (outDir == null || outDir.trim().length() == 0) ? "output" : outDir.trim();
        String rel = pkg.replace('.', File.separatorChar);
        File dir = new File(base, rel);
        if (!dir.exists()) dir.mkdirs();
        return new File(dir, className + ".java");
    }

    private void writeUtf8(File f, String s) throws Exception {
        FileOutputStream fos = null;
        OutputStreamWriter w = null;
        try {
            fos = new FileOutputStream(f);
            w = new OutputStreamWriter(fos, "UTF-8");
            w.write(s);
        } finally {
            if (w != null) try { w.close(); } catch (Exception ignore) {}
            if (fos != null) try { fos.close(); } catch (Exception ignore) {}
        }
    }

    private String upperFirst(String s) {
        if (s == null || s.length() == 0) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    private String escapeJavaString(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private boolean equalsIgnoreCaseTrim(String a, String b) {
        if (a == null || b == null) return false;
        return a.trim().equalsIgnoreCase(b.trim());
    }

    private String safeComment(ColumnMeta c) {
        if (c == null) return "";
        String cm = c.getComment();
        if (cm == null || cm.trim().length() == 0) return c.getColumnName();
        return cm.trim();
    }

    private String guessIdColumn(List<ColumnMeta> cols) {
        if (cols == null) return null;
        // 优先 JOB_ID
        for (int i = 0; i < cols.size(); i++) {
            String cn = cols.get(i).getColumnName();
            if (cn != null && "JOB_ID".equalsIgnoreCase(cn.trim())) return cn.trim();
        }
        // 其次 ID
        for (int i = 0; i < cols.size(); i++) {
            String cn = cols.get(i).getColumnName();
            if (cn != null && "ID".equalsIgnoreCase(cn.trim())) return cn.trim();
        }
        // 再次 *_ID
        for (int i = 0; i < cols.size(); i++) {
            String cn = cols.get(i).getColumnName();
            if (cn == null) continue;
            String s = cn.trim().toUpperCase();
            if (s.endsWith("_ID")) return cn.trim();
        }
        return null;
    }

    private String guessVersionColumn(List<ColumnMeta> cols) {
        if (cols == null) return null;
        for (int i = 0; i < cols.size(); i++) {
            String cn = cols.get(i).getColumnName();
            if (cn != null && "REC_VER".equalsIgnoreCase(cn.trim())) return cn.trim();
        }
        for (int i = 0; i < cols.size(); i++) {
            String cn = cols.get(i).getColumnName();
            if (cn != null && "VERSION".equalsIgnoreCase(cn.trim())) return cn.trim();
        }
        return null;
    }
}
