package org.demo.codegen.generator;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.util.List;

import org.demo.codegen.meta.ColumnMeta;
import org.demo.codegen.meta.TableMeta;

public class QueryConditionGenerator {

    public File generate(TableMeta table, String outDir, String queryPackage) throws Exception {
        if (table == null) throw new IllegalArgumentException("table is null");

        String pkg = resolvePackage(queryPackage);
        String className = table.getClassName() + "QueryCondition";

        File outFile = toJavaFile(outDir, pkg, className);
        writeJava(outFile, pkg, className, table.getColumns());
        return outFile;
    }

    public String resolvePackage(String pkgOrShort) {
        if (pkgOrShort == null || pkgOrShort.trim().length() == 0) {
            return "query";
        }
        return pkgOrShort.trim();
    }


    private File toJavaFile(String outDir, String pkg, String className) {
        String base = (outDir == null || outDir.trim().length() == 0) ? "output" : outDir.trim();
        String rel = pkg.replace('.', File.separatorChar);
        File dir = new File(base, rel);
        if (!dir.exists()) dir.mkdirs();
        return new File(dir, className + ".java");
    }

    private void writeJava(File outFile, String pkg, String className, List<ColumnMeta> cols) throws Exception {
        OutputStreamWriter w = null;
        try {
            w = new OutputStreamWriter(new FileOutputStream(outFile), "UTF-8");

            w.write("package " + pkg + ";\n\n");
            w.write("import java.util.Date;\n\n");
            w.write("/**\n");
            w.write(" * Generated by sql-query-codegen\n");
            w.write(" */\n");
            w.write("public class " + className + " {\n\n");

            // fields
            for (int i = 0; i < cols.size(); i++) {
                ColumnMeta c = cols.get(i);
                w.write("    private " + c.getJavaType() + " " + c.getJavaName() + ";\n");
                if (c.isTimeType()) {
                    w.write("    private Date " + c.getJavaName() + "From;\n");
                    w.write("    private Date " + c.getJavaName() + "To;\n");
                }
            }
            w.write("\n");

            // getters/setters
            for (int i = 0; i < cols.size(); i++) {
                ColumnMeta c = cols.get(i);
                String upper = upperFirst(c.getJavaName());

                w.write("    public " + c.getJavaType() + " get" + upper + "() {\n");
                w.write("        return " + c.getJavaName() + ";\n");
                w.write("    }\n\n");

                w.write("    public void set" + upper + "(" + c.getJavaType() + " " + c.getJavaName() + ") {\n");
                w.write("        this." + c.getJavaName() + " = " + c.getJavaName() + ";\n");
                w.write("    }\n\n");

                if (c.isTimeType()) {
                    w.write("    public Date get" + upper + "From() {\n");
                    w.write("        return " + c.getJavaName() + "From;\n");
                    w.write("    }\n\n");

                    w.write("    public void set" + upper + "From(Date " + c.getJavaName() + "From) {\n");
                    w.write("        this." + c.getJavaName() + "From = " + c.getJavaName() + "From;\n");
                    w.write("    }\n\n");

                    w.write("    public Date get" + upper + "To() {\n");
                    w.write("        return " + c.getJavaName() + "To;\n");
                    w.write("    }\n\n");

                    w.write("    public void set" + upper + "To(Date " + c.getJavaName() + "To) {\n");
                    w.write("        this." + c.getJavaName() + "To = " + c.getJavaName() + "To;\n");
                    w.write("    }\n\n");
                }
            }

            w.write("}\n");
        } finally {
            if (w != null) try { w.close(); } catch (Exception ignore) {}
        }
    }

    private String upperFirst(String s) {
        if (s == null || s.length() == 0) return s;
        if (s.length() == 1) return s.toUpperCase();
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }
}
