package org.demo.codegen.generator;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.util.List;

import org.demo.codegen.meta.ColumnMeta;
import org.demo.codegen.meta.TableMeta;

public class QueryItemGenerator {

    public File generate(TableMeta t, String outDir, String queryPackage) throws Exception {
        if (t == null) throw new IllegalArgumentException("TableMeta is null");

        String pkg = resolvePackage(queryPackage);
        String className = resolveQueryItemClassName(t);

        StringBuilder sb = new StringBuilder();

        // package
        if (pkg != null && pkg.trim().length() > 0) {
            sb.append("package ").append(pkg.trim()).append(";\n\n");
        }

        // imports
        sb.append("import javax.persistence.Column;\n");
        sb.append("import javax.persistence.Entity;\n\n");

        // javadoc
        sb.append("/**\n");
        sb.append(" * Generated by sql-query-codegen\n");
        sb.append(" * Table: ").append(t.getTableName()).append("\n");
        sb.append(" */\n");

        // class header
        sb.append("@Entity\n");
        // 关键：继承基类，提供 addValidField()
        sb.append("public class ").append(className).append(" extends BaseQueryItem {\n\n");

        // fields
        List<ColumnMeta> cols = t.getColumns();
        for (int i = 0; i < cols.size(); i++) {
            ColumnMeta c = cols.get(i);
            sb.append("    private ").append(c.getJavaType()).append(" ").append(c.getJavaName()).append(";\n");
        }
        sb.append("\n");

        // getters/setters with @Column and addValidField
        for (int i = 0; i < cols.size(); i++) {
            ColumnMeta c = cols.get(i);
            String type = c.getJavaType();
            String name = c.getJavaName();
            String upper = upperFirst(name);
            String col = c.getColumnName();

            // getter
            sb.append("    @Column(name = \"").append(escapeJavaString(col)).append("\")\n");
            sb.append("    public ").append(type).append(" get").append(upper).append("() {\n");
            sb.append("        return ").append(name).append(";\n");
            sb.append("    }\n\n");

            // setter + addValidField
            sb.append("    public void set").append(upper).append("(").append(type).append(" ").append(name).append(") {\n");
            sb.append("        this.").append(name).append(" = ").append(name).append(";\n");
            sb.append("        addValidField(\"").append(escapeJavaString(name)).append("\");\n");
            sb.append("    }\n\n");
        }

        sb.append("}\n");

        File f = toJavaFile(outDir, pkg, className);
        writeUtf8(f, sb.toString());
        return f;
    }

    public String resolvePackage(String pkgOrShort) {
        if (pkgOrShort == null || pkgOrShort.trim().length() == 0) {
            return "query";
        }
        return pkgOrShort.trim();
    }

    public String resolveQueryItemClassName(TableMeta t) {
        return t.getClassName() + "QueryItem";
    }

    private File toJavaFile(String outDir, String pkg, String className) {
        String base = (outDir == null || outDir.trim().length() == 0) ? "output" : outDir.trim();
        String rel = (pkg == null ? "" : pkg.trim()).replace('.', File.separatorChar);

        File dir = rel.length() == 0 ? new File(base) : new File(base, rel);
        if (!dir.exists()) dir.mkdirs();

        return new File(dir, className + ".java");
    }

    private void writeUtf8(File f, String s) throws Exception {
        FileOutputStream fos = null;
        OutputStreamWriter w = null;
        try {
            fos = new FileOutputStream(f);
            w = new OutputStreamWriter(fos, "UTF-8");
            w.write(s);
        } finally {
            if (w != null) try { w.close(); } catch (Exception ignore) {}
            if (fos != null) try { fos.close(); } catch (Exception ignore) {}
        }
    }

    private String upperFirst(String s) {
        if (s == null || s.length() == 0) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    private String escapeJavaString(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
